DjangoWebProjectVS2017/DjangoWebProjectVS2017/DjangoWebProjectVS2017/urls.py
"""
Definition of urls for DjangoWebProjectVS2017.
"""

from datetime import datetime
from django.conf.urls import include,url
from django.contrib import admin
import django.contrib.auth.views

import app.forms
import app.views
import app.models

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^user/', app.views.user_new, name='user'),
    url(r'^users/', app.views.users_detail, name='users_detail'),
    url(r'^chart/(?P<question_id>\d+)/$', app.views.chart, name='chart'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/add/', app.views.question_new, name='add'),
    url(r'^polls/choice_add/(?P<question_id>\d+)/$', app.views.choice_add, name='choice_add'),
    url(r'^(?P<question_id>\d+)/results/$', app.views.results, name='results'),
    url(r'^polls/(?P<question_id>\d+)/$', app.views.detail, name='detail'),
    url(r'^polls/(?P<question_id>\d+)/vote/$', app.views.vote, name='vote'),
    url(r'^polls/', app.views.index, name='index'),
    url(r'^quiz/add/', app.views.Quiz_question_new, name='qadd'),
    url(r'^quiz/choice_add/(?P<question_id>\d+)/$', app.views.Quiz_choice_add, name='qchoice_add'),
    url(r'^(?P<question_id>\d+)/qresults/$', app.views.Quiz_results, name='qresults'),####
    url(r'^(?P<question_id>\d+)/results/correct$', app.views.Quiz_results2, name='correct'),
    url(r'^(?P<question_id>\d+)/results/incorrect$', app.views.Quiz_results3, name='incorrect'),
    url(r'^quiz/(?P<question_id>\d+)/$', app.views.Quiz_detail, name='qdetail'),
    url(r'^quiz/(?P<question_id>\d+)/vote/$', app.views.Quiz_vote, name='qvote'),
    url(r'^quiz/$', app.views.Quiz_index, name='qindex'),
    #url(r'^quiz/(?P<topic_str>\w+)/$', app.views.Quiz_index_bytopic, name='qindexbytopic'),
    url(r'^quiz/chart/(?P<question_id>\d+)/$', app.views.Quiz_chart, name='qchart'),
   
]

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/models.py
"""
AQUI VAN LAS "CLASES"
"""

from django.db import models
from django.db.models.fields import CharField,BooleanField

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

TOPIC_CHOICES = [
    #(lo que se guardará, lo que se mostrará),
    ('Trabajo final HADS','Trabajo final HADS'),
    ('Evaluación HADS', 'Evaluación HADS'),
    ('Informática','Informática'),
    ('Otro','Otro'),
]

class Topic(models.Model):
    topic = models.CharField(max_length=18, choices= [('Todos','Todos')] + TOPIC_CHOICES)

class QuizQuestion(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    topic = models.CharField(max_length=18, choices=TOPIC_CHOICES, default='TFHADS')

class QuizChoice(models.Model):
    question = models.ForeignKey(QuizQuestion)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    correctAnswer = models.BooleanField(default=False)

class User(models.Model):
    email = models.CharField(max_length=200)
    nombre = models.CharField(max_length=200)

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/choice_new.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}</h2>
<h3>{{ topic }}</h3>

<h1>Insertar una opción</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        </form>
{% if error_message %}<p><strong style="color:red;"><b>{{ error_message }}</b></strong></p>{% endif %}
<a href="{% url 'qindex' %}">Ver preguntas</a> 

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/correct.html
{% extends "app/layout.html" %}
{% block content %}


<h1>Respuesta correcta!</h1>

<h3>{{ question.question_text }}</h3>


<a href="{% url 'qindex' %}">Contestar otra pregunta?</a>

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/detail.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
<h3>Pregunta: {{ question.question_text }}</h3>
<h3>Tema: {{question.topic}}</h3>
{% if error_message %}<p><strong style="color:red;"><b>{{ error_message }}</b></strong></p>{% endif %}
<form action="{% url 'qvote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.quizchoice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if request.user.is_authenticated and choice.correctAnswer %} checked {% endif %}/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
{% if request.user.is_authenticated %}
    <input type="submit" value="Seleccionar respuesta correcta" />
    <a href="{% url 'qchoice_add' question.id %}"><h3>Insertar Opciones</h3></a>
    <a href="{% url 'qresults' question.id %}"> <h3>Ver resultados de la votacion</h3> </a>
    <a href="{% url 'qchart' question.id %}"> <h3>Ver grafico de la votacion</h3> </a><br />  
{% else %}
    <input type="submit" value="Vote" />
{% endif %}

</form>
{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/grafico.html
{% extends "app/layout.html" %}
{% block content %}
<canvas id="myChart"></canvas> <br />
<a href="{% url 'qindex' %}"> Volver a las preguntas</a><br />
{% load i18n %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
    var options = {};
    var ctx = document.getElementById('myChart');
    var d = "{{dates}}".replace(/&quot;/g,"\"");
    var c = "{{counts}}".replace(/&quot;/g,"\"");
    var dates = JSON.parse( d );
    var counts = JSON.parse( c );
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: dates,
            datasets: [
                {
                    data: counts,
                    label: 'Choice',
                }
            ]},
         options: {
            scales: {
                yAxes: [{
                ticks: {
                beginAtZero: true
        }
      }]
    }
  }
    })
</script>
{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/incorrect.html
{% extends "app/layout.html" %}
{% block content %}

<h1>¡Respuesta incorrecta!</h1>
<h2>Más suerte la próxima vez</h2>

<h3>{{ question.question_text }}</h3>


<a href="{% url 'qindex' %}">Contestar otra pregunta?</a>

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/index.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<form action="" method="get">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Mostrar por tema" />
</form>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            {% if question.quizchoice_set.all|length >= 2 %}
                <a href="{% url 'qdetail' question.id %}">{{ question.question_text }}</a>
            {% elif request.user.is_authenticated %}
                <a href="{% url 'qdetail' question.id %}" style="color: red">{{ question.question_text }}</a>
            {% else %}
                {{ question.question_text }}
            {% endif %}
        </li>
    {% endfor %}
    </ul>
  
{% else %}
    <p>No quizzes are available.</p>
{% endif %}
{% if request.user.is_authenticated %}
<a href="{% url 'qadd' %}"><h2>Insertar pregunta</h2></a> 
{% endif %}

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/qresults.html
{% extends "app/layout.html" %}
{% block content %}

<h3>{{ msg }}</h3>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.quizchoice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} {% if request.user.is_authenticated and choice.correctAnswer %}-- Ésta es la respuesta correcta {% endif %}</li>
{% endfor %}
</ul>

<a href="{% url 'qchart' question.id %}"> Ver grafica</a><br />
<a href="{% url 'qindex' %}">Contestar otra pregunta?</a>

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/question_new.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h1>Insertar una pregunta</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
<a href="{% url 'qindex' %}">Ver preguntas</a> 

{% endblock %}

DjangoWebProjectVS2017/DjangoWebProjectVS2017/app/templates/quiz/results.html
{% extends "app/layout.html" %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.quizchoice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} {% if request.user.is_authenticated and choice.correctAnswer %}-- Ésta es la respuesta correcta {% endif %}</li>
{% endfor %}
</ul>

<a href="{% url 'qindex' %}">Contestar otra pregunta?</a>

{% endblock %}